name: K6 performance test
on:
  push:
    branches:
      - main

jobs:
  k6-performance-test-basic:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v2

      - name: step 2 - configuracao k6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: '0.49.0'
          browser: true
      - name: step 3 - execução do k6
        uses: grafana/run-k6-action@v1
        with:
          path: |
            ./script.js

  k6-performance-test-manual:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v2

      - name: step 2 - configuracao k6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: '0.49.0'
          browser: true

      - name: step 3 - execução manual k6
        run: |
          K6_WEB_DASHBOARD=true K6_WEB_DASHBOARD_EXPORT=report.html k6 run script.js --http-debug
          ls -la


  k6-performance-test-intermediario:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - run test
        uses: actions/checkout@v2
        uses: grafana/setup-k6-action@v1
        uses: grafana/run-k6-action@v1
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
          K6_WEB_DASHBOARD: true
          K6_WEB_DASHBOARD_EXPORT: report.html
        with:
          path: |
            ./script.js

      - name: step 3 - relatorio
        run: |
          ls -la
  