name: K6 performance test
on:
  push:
    branches:
      - main

jobs:
  k6-performance-test-basic:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v2

      - name: step 2 - configuracao k6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: '0.49.0'
          browser: true
      - name: step 3 - execução do k6
        uses: grafana/run-k6-action@v1
        with:
          path: |
            ./script.js

  k6-performance-test-maual:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v2

      - name: step 2 - configuracao k6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: '0.49.0'
          browser: true

      - name: step 3 - execução manual k6
        run: |
          k6 K6_WEB_DASHBOARD=true K6_WEB_DASHBOARD_EXPORT=report.html run script.js --vus 10 --duration 30s --http-debug
          ls -la


  k6 performance-test-intermediario:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: grafana/run-k6-action@v1
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
          URL: www.example.com
        with:
          path: |
            ./script.js
  